Error processing file jt19.java: len(predToken) != len(codeError)
Traceback (most recent call last):
  File "framework.py", line 238, in run_lib
    result,iter_round = iterative_execute_one_snippet(file_name,dataset,lib,topK,build_kb_with_extension,StartFromRule,log_feed_back_flag,Maximum_iter_round)
  File "framework.py", line 119, in iterative_execute_one_snippet
    dl_node_pred_dict,dl_node_truth_dict = run_baseline.DL_predict_one_snippet(snippet_file_name,dataset,lib,3)
  File "/iJTyper/Baseline/run_baseline.py", line 199, in DL_predict_one_snippet
    DL.Itera_Pred(lib,Model_path)
  File "/iJTyper/Baseline/Prompt_tune/ASE_prompt_tuning/PromptInference/Practicality/predDictData_line.py", line 48, in __init__
    self.file_read()
  File "/iJTyper/Baseline/Prompt_tune/ASE_prompt_tuning/PromptInference/Practicality/predDictData_line.py", line 67, in file_read
    self.Start(code_file)
  File "/iJTyper/Baseline/Prompt_tune/ASE_prompt_tuning/PromptInference/Practicality/predDictData_line.py", line 83, in Start
    self.file_writer()  # 输入: self.out_sequence 和 self.codeErrorInfo
  File "/iJTyper/Baseline/Prompt_tune/ASE_prompt_tuning/PromptInference/Practicality/predDictData_line.py", line 335, in file_writer
    assert len(predToken_list) == len(codeError_list),'len(predToken) != len(codeError)'
AssertionError: len(predToken) != len(codeError)

