Error processing file hb3.java: len(predToken) != len(codeError)
Traceback (most recent call last):
  File "framework.py", line 254, in run_lib
    result,iter_round = iterative_execute_one_snippet(file_name,dataset,lib,topK,build_kb_with_extension,StartFromRule,log_feed_back_flag,Maximum_iter_round)
  File "framework.py", line 99, in iterative_execute_one_snippet
    dl_node_pred_dict,dl_node_truth_dict = DL_predict_with_Rule_info(snippet_file_name,dataset,lib,topK,rule_node_pred_dict)
  File "/iJTyper/ours/deeplearning.py", line 217, in DL_predict_with_Rule_info
    Pred_with_Prompt_Augmented(lib,Model_path,rule_node_pred_dict)
  File "/iJTyper/ours/deeplearning.py", line 40, in __init__
    self.file_read()
  File "/iJTyper/Baseline/Prompt_tune/ASE_prompt_tuning/PromptInference/Practicality/predDictData_line.py", line 67, in file_read
    self.Start(code_file)
  File "/iJTyper/Baseline/Prompt_tune/ASE_prompt_tuning/PromptInference/Practicality/predDictData_line.py", line 83, in Start
    self.file_writer()  # 输入: self.out_sequence 和 self.codeErrorInfo
  File "/iJTyper/Baseline/Prompt_tune/ASE_prompt_tuning/PromptInference/Practicality/predDictData_line.py", line 335, in file_writer
    assert len(predToken_list) == len(codeError_list),'len(predToken) != len(codeError)'
AssertionError: len(predToken) != len(codeError)

